### ISSUE TITLE
Optimization for static videos

### ISSUE THREAD

**Issue by hahiserw** [TheAMM/mpv_thumbnail_script#16]
I've set thumbnail_network=yes
And as you know there are some music videos with static image and I was wondering if it could be optimized, so that only one thumbnail would be generated instead of default 150.
It's not that big of a deal, but would be easier on cpu.

**Comment by TheAMM** [comment]
There's no way for me to reliably check if a video consists of a single static frame. It would technically possible to check if the preliminary frames are similar enough (identical is too accurate because life is lossy) and then fill the gaps with the existing all-similar frames, but that's a whole lot of code for a silly niche feature, which will be funny when it'll break thumbnailing for files which happen to have the same frame at the start and end etc.
I'll likely (eventually, when I return to Lua scripting) add an option to limit remote thumbnails, or a path wildcard to disable auto-generation, or something, but for now, you'll have to disable automatic thumbnail generation and use a keybind if you want to avoid thumbnailing static videos.
