### ISSUE TITLE
Thumbnail generation gets stuck

### ISSUE THREAD

**Issue by OkuuZaki** [TheAMM/mpv_thumbnail_script#69]
Nice project, I really like it! Unfortunately in my Win10 machine, the thumbnail generation seems to get stuck at seemingly random when generating the thumbnails. It initializes and starts generating thumbnails, then it gets stuck after generating some amount of them. This can happen in the very first frame, or some of the middle ones. When closing the program and reopening it continues the generation and sometimes even finishes given enough times to restart.

I did some preliminary debugging and the thumbnail script server stops at line 652 during processing the thumbnail_func function. I noticed that the script leaves a log file instead of a thumbnail in these kind of situations so I will attach the log file of the frame that did not succeed at the thumbnail generation.
[000019.bgra.log](https://github.com/TheAMM/mpv_thumbnail_script/files/4902086/000019.bgra.log)

The thumbnail script server also seems to be able to continue when exiting mpv, just before the thumbnail script server is killed. I noticed this as the debugging warning I added after the thumbnail_func popped when exiting mpv:
[cplayer] EOF code: 5
[ad] Uninit decoder.
[vd] Uninit decoder.
[cplayer] finished playback, success (reason 3)
[cplayer]
[cplayer]
[cplayer] Exiting... (Quit)
[vo/gpu/d3d11] shaderc compile status 'success' (0 errors, 0 warnings)
[betterchaptersupdated] Exiting...
[ytdl_hook] Exiting...
[mpv_thumbnail_script_server_2] Stage2.2 on thumbnail 19 table: 0x04d144a0    <-- My debugging note
[stats] Exiting...
[autoload] Exiting...
[mpv_thumbnail_script_client_osc] Exiting...
[vo/gpu/d3d11] Compiled a vertex shader in 4952us
[vo/gpu/d3d11] shaderc: 3362us, SPIRV-Cross: 125us, D3DCompile: 1465us
[mpv_thumbnail_script_server_2] Changing files, subprocess killed
[mpv_thumbnail_script_server_2] Exiting...

I have tried this with one and two servers at the same time but the problem still remains. Has someone had similar problems or maybe I'm missing something obvious?

**Comment by OkuuZaki** [comment]
Ok, so after a bit of a break from this, I realized I had almost an year old build of mpv. I did an update to the most recent win build (mpv-x86_64-20200809-git-bb23188) and tried it out. I had a similar error as here:

https://github.com/TheAMM/mpv_thumbnail_script/issues/66#issue-624574875

So I tried out the solution suggested in that post and now it seems to work as suggested!

**Comment by automatata** [comment]
This script works by injecting custom code into a file `player/lua/osc.lua` from the upstream mpv source, to produce the file `src/
patched_osc.lua` in this repository. From time to time when you update mpv built with an updated `osc.lua`, this script may stop working. Basically someone has to redo the code injection on the new `osc.lua` to produce a new `patched_osc.lua` then compile the final server and client scripts with the `concat_files.py` mentioned in the front page.

Since the author seems to be inactive for a while, we may do the above ourselves next time. The current `patched_osc.lua` says

```lua
--[[
This is mpv's original player/lua/osc.lua patched to display thumbnails
Sections are denoted with -- mpv_thumbnail_script.lua --
Current osc.lua version: 97816bbef0f97cfda7abdbe560707481d5f68ccd
]]--
```

meaning its base source is https://raw.githubusercontent.com/mpv-player/mpv/97816bbef0f97cfda7abdbe560707481d5f68ccd/player/lua/osc.lua.

I just tried to use standard `git merge` to merge the edits in the latest `osc.lua` with the edits in `patched_osc.lua`, and it was smoothly successful without nasty merge conflicts. Actually the edits in `patched_osc.lua` only occurred in a few chunks, so you may redo the edits in the newest `osc.lua` manually, too.
